<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoneyWay.Application\MoneyWay.Application.csproj" />
    <ProjectReference Include="..\MoneyWay.Infrastructure\MoneyWay.Infrastructure.csproj" />
  </ItemGroup>

</Project>
