namespace MoneyWay.Application.StrategyReplay.Capabilities;

/// <summary>Provides explicit audited MoneyWay evaluation limitations without inferring them from rule definition status.</summary>
public static class MoneyWayReplayEvaluationCapabilityDeclarations
{
    private const string ForexSource = "docs/strategies/forex/rule-catalog.md";
    private const string NasdaqSource = "docs/strategies/nasdaq/rule-catalog.md";

    public static IReadOnlyList<ReplayRuleEvaluationCapabilityDeclaration> GetAll() =>
    [
        Blocked("moneyway-forex", "forex-0.1.0-draft", "FX-W-004", "The exact weekly-zone interaction tolerance remains unresolved.", ForexSource),
        Blocked("moneyway-forex", "forex-0.1.0-draft", "FX-BO-001", "The deterministic breakout geometry remains unresolved.", ForexSource),
        Blocked("moneyway-forex", "forex-0.1.0-draft", "FX-RT-001", "The deterministic retest tolerance and invalidation rules remain unresolved.", ForexSource),
        Blocked("moneyway-forex", "forex-0.1.0-draft", "FX-TP-001", "The deterministic exit policy for the reference reward/risk ratio remains unresolved.", ForexSource),
        Blocked("moneyway-nasdaq", "nasdaq-0.1.0-draft", "NQ-H4-001", "Deterministic 4H structural context evaluation remains blocked, although bullish candidate-HL reconstruction is partially defined: the prior HH is the upper boundary, the first bearish candle after HH production stops starts the correction, deeper lows replace shallower candidates while it remains active, and only a formally closed Close > prior HH validates the candidate from that causal AsOfUtc. Within a selected turn, the lowest Open or Close body price is source-supported and an isolated wick is insufficient. Direct bearish evidence establishes the prior LL as the correction origin/reference: a candidate high remains provisional until a formally closed Close < prior LL confirms the new LL and validates the preceding highest candidate high as LH only from that causal AsOfUtc; wick-only penetration and an open candle do not confirm it. Within one recognized bearish correction, a higher candidate high replaces a lower candidate and superseded intermediate highs do not survive as LH. This confirms LH structural identity and its selected-turn structural coordinate: the highest Open or Close body edge; candle color does not alter it and a higher wick does not redefine it. This body-based coordinate is distinct from the separate SELL Stop Loss anchor above the highest wick/tail of the relevant structural 5M LH. The causal confirming candle is excluded from the correction set and retrospective candidate HL/LH scan, belongs conceptually to the impulsive leg, and its formally closed Close validates the new HH/LL and preceding candidate only from that causal AsOfUtc. A single expansive confirming candle may also contain impulse-origin evidence without becoming a correction candle; its exact origin-price coordinate, intrabar chronology, and synthetic path remain unresolved. Reproducible bearish correction boundaries and segmentation, including Doji/gap handling, exact prior HH/LL boundary inclusivity, and turn membership remain unresolved. A reproducible visual bootstrap, equal-coordinate candle identity, and other structural coordinates remain unresolved.", NasdaqSource),
        Blocked("moneyway-nasdaq", "nasdaq-0.1.0-draft", "NQ-M5-004", "The deterministic IFVG geometry remains unresolved.", NasdaqSource),
        Blocked("moneyway-nasdaq", "nasdaq-0.1.0-draft", "NQ-SL-001", "Deterministic identification of the relevant structural 5M HL/LH and executable Stop Loss geometry remain unresolved. For sells, the conceptual Stop Loss anchor is above the highest wick/tail of the relevant structural 5M LH. This does not define a buffer, offset, spread or cost adjustment, broker order price, execution semantics, or a structural target coordinate.", NasdaqSource),
        Blocked("moneyway-nasdaq", "nasdaq-0.1.0-draft", "NQ-TP-001", "Session target candidates, distinct first-encountered priority, and equal-target merge are source-defined. Structural fallback is partially defined: its candidate families include relevant unmitigated 1H/4H HL/LL support or Previous Day Low for sells and 1H/4H LH/HH resistance or Previous Day High for buys; the reviewed 1H-first/4H-extended relationship is source-supported, not universal. Bullish candidate-HL reconstruction is partially defined: the prior HH is the upper boundary, the first bearish candle after HH production stops starts the correction, deeper lows replace shallower candidates while it remains active, and only a formally closed Close > prior HH makes the candidate usable from that causal AsOfUtc. Within a selected turn, the lowest Open or Close body price is source-supported and an isolated wick is insufficient. Direct bearish evidence establishes the prior LL as the correction origin/reference: a candidate high remains provisional until a formally closed Close < prior LL confirms the new LL and validates the preceding highest candidate high as LH only from that causal AsOfUtc; wick-only penetration and an open candle do not confirm it. Within one recognized bearish correction, a higher candidate high replaces a lower candidate and superseded intermediate highs do not survive as LH. This confirms candidate-LH identity and its selected-turn target structural coordinate: the highest Open or Close body edge; candle color does not alter it and a higher wick does not redefine it. This body-based target coordinate is distinct from the separate SELL Stop Loss anchor above the highest wick/tail of the relevant structural 5M LH; neither substitutes for the other. The causal confirming candle is excluded from the correction set and retrospective candidate HL/LH scan, belongs conceptually to the impulsive leg, and its formally closed Close validates the new HH/LL and preceding candidate only from that causal AsOfUtc. A single expansive confirming candle may also contain impulse-origin evidence without becoming a correction candle; its exact origin-price coordinate, intrabar chronology, and synthetic path remain unresolved. Reproducible bearish correction boundaries and segmentation, including Doji/gap handling, exact prior HH/LL boundary inclusivity, and turn membership remain unresolved. Equal-coordinate candle identity, other structural-point selection and coordinates, exact OHLC mitigation test, PDH/PDL cross-class ranking, and ties or coincidences remain unresolved. General final Take Profit hierarchy outside the reviewed cases and universal full-exit behavior also remain unresolved.", NasdaqSource),
    ];

    private static ReplayRuleEvaluationCapabilityDeclaration Blocked(string strategyId, string version, string ruleId, string reason, string source) =>
        new(new(strategyId), new(version), new(ruleId), ReplayRuleEvaluationCapabilityStatus.BlockedByUnresolvedSpecification, reason, source);
}
